INPUT_DATA_PATH = "./9_10_11月_user_behavior_processed_sampled_0111"
OUTPUT_DIR = "./output"
RESULTS_DIR = "./results"

USE_FIXED_EXPERIMENT_DATA = True
FIXED_EXPERIMENT_DATA_PATH = "./dataset/experiment_data.json"

MAX_HISTORY_TOKENS = 0
DEBUG_PARSING = False

HISTORY_PROCESS_MODE = "none"

SUMMARY_CONFIG = {
    "model_name": "YOUR_MODEL_NAME",
    "api_key": "YOUR_API_KEY",
    "temperature": 0.3,
    "enable_thinking": False,
    "endpoints": [
        {"url": "http://your-model-endpoint/v1", "max_workers": 10},
    ],
    "buffer_max_tokens": 4096,
    "max_summary_tokens": 1000,
    "runtime_summary_threshold": 0.5,
    "cache_dir": "./.summary_cache",
}

RAG_CONFIG = {
    "embedding_type": "local",
    "embedding_model": "/path/to/bge-m3",
    "device": "cuda",
    "batch_size": 512,
    "multi_gpu": True,
    "gpu_ids": [0, 1, 2, 3, 4, 5, 6, 7],
    "min_multiprocess_batch": 32,
    "query_batch_size": 64,
    "use_fp16": True,
    "pin_memory": True,
    "num_workers": 4,
    "doc_embed_batch_size": 64,
    "actions_per_doc": 8,
    "max_doc_chars": 6000,
    "show_embed_progress": True,
    "log_gpu_usage": True,
    "profile_embedding": False,
    "api_key": None,
    "base_url": None,
    "top_k": 100,
    "chunk_size": 500,
    "chunk_overlap": 50,
    "max_seq_length": 512,
    "use_cache": True,
    "cache_dir": "./.rag_cache",
    "oversample_factor": 5,
    "max_search_k": 200,
    "embedding_dim": 1024,
    "index_max_days": 92,
}


MODELS_TO_EVALUATE = [
    {
        "name": "gpt-oss-120b",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 128},
        ],
        "model": "gpt-oss-120b",
        "temperature": 0.1,
        "max_workers": 100,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": False,
    },
    {
        "name": "Qwen2.5-72B-Instruct",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-model-endpoint/v1",
        "model": "Qwen2.5-72B-Instruct",
        "temperature": 0.1,
        "max_workers": 100,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
    },
    {
        "name": "AWS-Claude-3.7",
        "type": "aws_claude",
        "aws_access_key_id": "YOUR_AWS_ACCESS_KEY_ID",
        "aws_secret_access_key": "YOUR_AWS_SECRET_ACCESS_KEY",
        "temperature": 0.7,
        "max_workers": 5,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": False,
    },
    {
        "name": "Qwen3-Next-80B-A3B-Instruct",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-model-endpoint/v1",
        "model": "/path/to/Qwen3-Next-80B-A3B-Instruct",
        "temperature": 0.7,
        "max_workers": 50,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
    },
    {
        "name": "Qwen3-8B",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 40},
        ],
        "model": "Qwen3-8B",
        "temperature": 0.1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    },
    {
        "name": "Qwen3-14B",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 40},
        ],
        "model": "Qwen3-14B",
        "temperature": 0.1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    },
    {
        "name": "Qwen3-32B",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 20},
        ],
        "model": "Qwen3-32B",
        "temperature": 0.1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    },
    {
        "name": "Qwen3-235B",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 2},
        ],
        "model": "Qwen3-235B",
        "temperature": 0.1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
    },
    {
        "name": "Qwen3-Max",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 10,
        "rpm": 100,
        "tpm": 1000000,
        "use_logprobs": True,
    },
    {
        "name": "Gemini-3-Flash-Preview",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 20,
        "rpm": 100,
        "tpm": 4000000,
        "use_logprobs": False,
    },
    {
        "name": "Gemini-3-Pro-Preview",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 10,
        "rpm": 200,
        "tpm": 5000000,
        "use_logprobs": False,
    },
    {
        "name": "Doubao-1.5-Pro",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "max_workers": 20,
        "rpm": 200,
        "tpm": 5000000,
        "use_logprobs": True,
    },
    {
        "name": "GLM-4.7",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "endpoints": [
            {"url": "http://your-model-endpoint/v1", "max_workers": 1},
        ],
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": True,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    },
    {
        "name": "GPT-4o",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 30,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": True,
    },
    {
        "name": "GPT-4o-mini",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 30,
        "rpm": 300,
        "tpm": 10000000,
        "use_logprobs": True,
    },
    {
        "name": "GPT-5",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "is_reasoning_model": True,
        "temperature": 0.1,
        "max_workers": 10,
        "rpm": 200,
        "tpm": 5000000,
        "use_logprobs": False,
    },
    {
        "name": "deepseek-chat",
        "type": "openai_compatible",
        "api_key": "YOUR_DEEPSEEK_API_KEY",
        "base_url": "https://api.deepseek.com",
        "model": "deepseek-chat",
        "temperature": 0.1,
        "max_workers": 20,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": False,
    },
    {
        "name": "Claude-Haiku-4.5",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 5,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": False,
        "use_cache_control": True,
    },
    {
        "name": "Claude-Sonnet-4.5",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 10,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": False,
        "use_cache_control": True,
    },
    {
        "name": "Claude-Sonnet-4.5-novita",
        "type": "openai_compatible",
        "api_key": "YOUR_NOVITA_API_KEY",
        "base_url": "https://api.novita.ai/v3/openai/v1",
        "model": "pa/claude-sonnet-4-5-20250929",
        "temperature": 0.1,
        "max_workers": 50,
        "rpm": 0,
        "tpm": 0,
        "use_cache_control": True,
    },
    {
        "name": "Claude-Sonnet-4",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 10,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": False,
        "use_cache_control": True,
    },
    {
        "name": "Kimi-K2-Instruct",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 20,
        "rpm": 200,
        "tpm": 8000000,
        "use_logprobs": True,
    },
    {
        "name": "MiniMax-M2.1",
        "type": "openai_compatible",
        "api_key": "YOUR_API_KEY",
        "base_url": "http://your-api-gateway/v1",
        "model": "YOUR_MODEL_ID",
        "temperature": 0.1,
        "max_workers": 1,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": False,
    },
    {
        "name": "Claude-3-Sonnet-test",
        "type": "anthropic",
        "api_key": "YOUR_ANTHROPIC_API_KEY",
        "model": "claude-3-sonnet-20240229",
        "temperature": 0.7,
        "rpm": 0,
        "tpm": 0,
        "use_logprobs": False,
    },
]

BINARY_CLASSIFICATION_MAX_RETRIES = 10
